### ISSUE TITLE
The horizontal guide is not shown when x-Height is missing in font info

### ISSUE THREAD

**Issue by boomwooq** [Mark2Mark/show-stems-pro-plugin#10]
Hi Mark, 
I'm unsure why my horizontal measurement is not shown; I'm on the Pro version— Glyphs 3 (3.2 (3207)). Noted that it was like this even before I updated to the cutting-edge version; In case there are some settings I don't know about. 

Thank you in advance! 
Boom 

<img width="470" alt="CleanShot 2023-07-22 at 12 44 31@2x" src="https://github.com/Mark2Mark/show-stems-pro-plugin/assets/15804957/5a88e8b8-f377-4d9e-af68-532f7b01c35e">
<img width="598" alt="CleanShot 2023-07-22 at 12 46 07@2x" src="https://github.com/Mark2Mark/show-stems-pro-plugin/assets/15804957/37f36e11-cdf1-4ddb-b595-56a617a196f6">
<img width="606" alt="CleanShot 2023-07-22 at 12 46 29@2x" src="https://github.com/Mark2Mark/show-stems-pro-plugin/assets/15804957/808d09f5-ec93-49aa-a3e8-93f9405b6383">

**Comment by Mark2Mark** [comment]
Hi @boomwooq,

Thanks for the report. Maybe it is just out of the view somehow.

would you mind to run this from your Macro Panel and let me know what it prints out?

```python
print(Glyphs.defaults["com_markfromberg_ShowStems_horizontalBeamPosition"])
print(Glyphs.defaults["com_markfromberg_ShowStems_verticalBeamPosition"])
```

it should print two numbers, both with somehow rational values. From that result we can investigate further.

**Comment by boomwooq** [comment]
Hi @Mark2Mark 
I run the first one; here is the result. But the second one doesn't show/ change anything even turn on and off plug-in. Another thing I found is that when it's not in the Italic setting, the plug-in works normally. 
<img width="988" alt="CleanShot 2023-07-23 at 10 53 52@2x" src="https://github.com/Mark2Mark/show-stems-pro-plugin/assets/15804957/78fe9cae-6c5b-4d4c-ac50-37f299834cef">

**Comment by Mark2Mark** [comment]
Thanks, @boomwooq!

1. After you run the second one (which sets the horizontal beam to 300) does the first one then print 300?
2. What do you mean with Italic setting? You mean the checkbox under Vertical Beam > Italic Angled?
3. can you check which version you got? For this please run this from the Macro Panel:
```py
from AppKit import NSBundle
bdl = NSBundle.bundleForClass_(NSClassFromString('Show_Stems_Pro'))
print(bdl.objectForInfoDictionaryKey_('CFBundleShortVersionString'))
```

**Comment by boomwooq** [comment]
@Mark2Mark 
1. Yes, it changed, but the horizontal line is still invisible. 
2. I mean when the italic angle is set in Metrics in Glyphs info.
3. My version is 3.1.9


https://github.com/Mark2Mark/show-stems-pro-plugin/assets/15804957/dc7f8ced-a6da-4799-9e64-02c25eab37c4
<img width="664" alt="CleanShot 2023-07-23 at 11 15 13@2x" src="https://github.com/Mark2Mark/show-stems-pro-plugin/assets/15804957/2a85201f-1aed-4e7d-b29c-40151ce471c3">

**Comment by Mark2Mark** [comment]
Thanks @boomwooq,

I just pushed an update. Not sure if it fixes it yet, but since that version works for me, maybe it does so for you too.

To get it quickly, you could uninstall the plugin and re-install it in Glyphs. Otherwise it could take a while for Glyphs to recognize that there is an update. If you run the version checking script, it should say `3.2.0`.

Let mw know how it goes. Also much apologies for the inconvenience and thanks for your patience.

**Comment by boomwooq** [comment]
@Mark2Mark Thank you for the update! I did update to the new version. It's super odd to me why it still doesn't work, so I decided to check with other files, and it seems to be ok. So I decided to create the new file **with the same setting**.. went through a bit of transferring stuff and now it works!

Anyway, I'm just here to update you! Thank you again for your help!
<img width="1198" alt="CleanShot 2023-07-23 at 12 03 40@2x" src="https://github.com/Mark2Mark/show-stems-pro-plugin/assets/15804957/ee425983-3da2-4421-ad44-b69049a01c66">

**Comment by boomwooq** [comment]
@Mark2Mark Oh wait, I figured it out!
So the old file, I started by setting up the file in Thai script the right way without having an x-height value. And that's why it didn't show. As soon as I set up the x-height value, the line shows! Sorry for this!

**Comment by Mark2Mark** [comment]
@boomwooq thanks for this!

I think it has to do with the italic angle calculation, as that requires the xHeight (half of it actually) to determine the italic shifting for coordinates.

I think there is not much I can do about it, other than ask the user to have an xHeight set in the file.

- [ ] Add notification to user, if xHeight is missing.
